[project]
name = "beautify-wechat-article"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "markdown>=3.5.0",
    "fastapi>=0.104.0",
    "uvicorn>=0.24.0",
]
